### ISSUE TITLE
Brazilian Portuguese

### ISSUE THREAD

**Issue by alexandresn** [CanopyTax/single-spa.js.org#562] opened 2022-09-23 14:38 UTC
Hi. I coudn't see a translation to Brazilian Portuguese. Do you have any predict when it will be available?

**Comment by filoxo** [comment] 2022-09-23 15:36
Duplicate of #504. There is no expected time, as translations are community driven and no one has sponsored the work.

**Closed as completed by filoxo** 2022-09-23 15:36 UTC
